FROM emscripten/emsdk:1.39.18

ENV EMCC_CORES=1
ENV BOOST_INCLUDE_DIR=/opt/local/include

RUN curl -L https://archives.boost.io/release/1.73.0/source/boost_1_73_0.tar.gz \
      -o /tmp/boost.tar.gz \
 && mkdir -p "$BOOST_INCLUDE_DIR" \
 && tar xzf /tmp/boost.tar.gz \
      --strip-components=1 \
      -C "$BOOST_INCLUDE_DIR" \
      boost_1_73_0/boost \
 && rm /tmp/boost.tar.gz

WORKDIR /app
